from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create/', views.create_campaign, name='create_campaign'),
    path('create/edit/<int:campaign_id>/', views.edit_campaign_view, name='edit_campaign'),
    path('create/delete/<int:campaign_id>/', views.delete_campaign_view, name='delete_campaign'),
    path('my-donations/', views.my_donations_view, name='my_donations'),
    path('all-donations/', views.all_donations_view, name='all_donations'),
    path("donations_list/", views.donations_list, name="donations_list"),
    path('delete-campaign/<int:campaign_id>/', views.delete_campaign_view, name='delete_campaign'),
    path('edit-campaign/<int:campaign_id>/', views.edit_campaign_view, name='edit_campaign'),
    path('profile/', views.profile_view, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('education/', views.education_view, name='education'),
    path('food/', views.food_view, name='food'),
    path('clothes/', views.clothes_view, name='clothes'),
    path('medical/', views.medical_view, name='medical'),
    path('infrastructure/', views.infrastructure_view, name='infrastructure'),
    path('shelter/', views.shelter_view, name='shelter'),
    path('donate/<int:campaign_id>/', views.donation_view, name='donate'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('approved_donations/', views.approved_donations, name='approved_list'),
    path('contact-admin/', views.contact_admin, name='contact_admin'),
    path('view-queries/', views.view_queries, name='view_queries'),
    path('admin-approval/', views.admin_approval_panel, name='admin_approval_panel'),
    path('approve/<int:donation_id>/', views.approve_donation, name='approve_donation'),
    path('reject/<int:donation_id>/', views.reject_donation, name='reject_donation'),
    path('reply/<int:query_id>/', views.reply_to_query, name='reply_to_query'),
    path('request-assistance/', views.request_assistance, name='request_assistance'),
    path('recipient-requests/', views.admin_recipient_requests, name='admin_recipient_requests'),
    path('approve_request/<int:request_id>/', views.approve_recipient_request, name='approve_recipient_request'),
    path('reject_request/<int:request_id>/', views.reject_recipient_request, name='reject_recipient_request'),
    path('request/', views.recipient_request_form, name='recipient_request_form'),
    path('my_request_status/', views.my_request_status, name='my_request_status'),
]